// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ6wBGazyiSulHhta3xingcvyJkvf6VHs',
    appId: '1:963422119423:web:505f892fd5ac458802f3ca',
    messagingSenderId: '963422119423',
    projectId: 'swift-cafe-3e7c2',
    authDomain: 'swift-cafe-3e7c2.firebaseapp.com',
    storageBucket: 'swift-cafe-3e7c2.appspot.com',
    measurementId: 'G-G6W7J3LXWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlqeEVYFYA0KdB1AXTqEN8oZQEEp8nhA',
    appId: '1:963422119423:android:1b2301f16ef26dfa02f3ca',
    messagingSenderId: '963422119423',
    projectId: 'swift-cafe-3e7c2',
    storageBucket: 'swift-cafe-3e7c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHmEVuFnWOrL22Vqg7lPnViHJEHMu3DH0',
    appId: '1:963422119423:ios:f6c6ae26f4d7f64002f3ca',
    messagingSenderId: '963422119423',
    projectId: 'swift-cafe-3e7c2',
    storageBucket: 'swift-cafe-3e7c2.appspot.com',
    iosBundleId: 'com.example.swiftCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHmEVuFnWOrL22Vqg7lPnViHJEHMu3DH0',
    appId: '1:963422119423:ios:c2106ed6917fa89a02f3ca',
    messagingSenderId: '963422119423',
    projectId: 'swift-cafe-3e7c2',
    storageBucket: 'swift-cafe-3e7c2.appspot.com',
    iosBundleId: 'com.example.swiftCafe.RunnerTests',
  );
}
